sudo: 'required'
language: generic

services:
  - docker

after_success:
  - docker build -t abdulsammad200/aldovia ./server
  # Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - echo "$HEROKU_AUTH_TOKEN" | docker login --username=_ --password-stdin registry.heroku.com
  # Push
  - docker push abdulsammad200/aldovia
  - heroku container:push abdulsammad200/aldovia -a aldovia
  # Release
  - heroku container:release abdulsammad200/aldovia -a aldovia